# # Uncomment the next line to define a global platform for your project
# # platform :ios, '9.0'

# target 'ConnectMe' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for ConnectMe
#   # Pods for ThamesClippers
#   pod 'Google/Analytics'
#   pod 'Firebase/Core'
#   pod 'Firebase/AdMob'

#   # Trying to fix GoogleToolboxForMac missing error
#   pod 'Firebase/Messaging'
#   pod 'GoogleToolboxForMac/Logger' 
#   pod 'GoogleToolboxForMac', '~> 2.1'

#   target 'ConnectMeTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

# target 'ConnectMe-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for ConnectMe-tvOS

#   target 'ConnectMe-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end

# Uncomment the next line to define a global platform for your project
platform :ios, '10.2'
source 'git@github.com:evernym/connect-me-indy-wrapper.git'
source 'git@github.com:hyperledger/indy-sdk.git'
source 'https://github.com/CocoaPods/Specs.git'

pod 'ConnectMeIndy', '0.0.33'
pod 'Firebase/Messaging', '4.8.0'

target 'ConnectMe' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SimpleFcmClient

  target 'ConnectMeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CLANG_ENABLE_OBJC_WEAK'] ||= 'YES'
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.3'
        end
    end
end


