fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  before_all do
     ENV["SLACK_URL"] = "https://evernym.slack.com/messages/C53EUR2U9/"
  end

  lane :beta do
      increment_build_number(xcodeproj: "ConnectMe.xcodeproj")
      app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
      match(
        type: "adhoc",
        app_identifier: "#{app_identifier}",
        force_for_new_devices: true
      )
      disable_automatic_code_signing(path: "ConnectMe.xcodeproj")
      profile = ENV["sigh_#{app_identifier}_adhoc"]
      gym(
        scheme: "ConnectMe",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile}' DEVELOPMENT_TEAM='ES8QU3D2A4'",
        clean: true
      )
      hockey(api_token: "27ccf5014490440fa0d9ffd75a836ed9") 
  end
  
  after_all do |lane|
     slack(channel: "fastlane", message: "Successfully deployed new App update on hockeyapp.")
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end
