fastlane_version "2.27.0"

default_platform :ios

platform :ios do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
  end

  lane :beta do
      reset_git_repo(force: true)
      increment_build_number(xcodeproj: "ConnectMe.xcodeproj")
      app_identifier = CredentialsManager::AppfileConfig.try_fetch_value(:app_identifier)
      match(
        type: "adhoc",
        app_identifier: "#{app_identifier}",
        force_for_new_devices: true
      )
      disable_automatic_code_signing(path: "ConnectMe.xcodeproj")
      profile = ENV["sigh_#{app_identifier}_adhoc"]
      gym(
        scheme: "ConnectMe",
        xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{profile}' DEVELOPMENT_TEAM='ES8QU3D2A4'",
        clean: true
      )
      remote_branch = ENV["BITRISE_GIT_BRANCH"]

      if remote_branch == "master"
        hockey(api_token: ENV["QA_HOCKEYAPP_TOKEN"])
      elsif remote_branch == "stage"
        hockey(api_token: ENV["STAGE_HOCKEYAPP_TOKEN"])
      else
        hockey(api_token: ENV["DEV_HOCKEYAPP_TOKEN"])
      end

      commit_version_bump(
        message: "Build Version bump by Fastlane [ci skip]",
        xcodeproj: "ConnectMe.xcodeproj",
        force: true
      )
      push_to_git_remote(
        remote: "origin",         
        local_branch: "HEAD",  
        remote_branch: "#{remote_branch}",
        force: true,
        tags: false
      )
  end

  after_all do |lane|
     slack(channel: "connectme_build", message: "Successfully deployed new App update on hockeyapp.")
  end

  error do |lane, exception|
     slack(
       channel: "connectme_build",
       message: exception.message,
       success: false
     )
  end
end
