fastlane_version "2.27.0"

default_platform :android
platform :android do
  before_all do
     ENV["SLACK_URL"] = "https://hooks.slack.com/services/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"
end
  
lane :alpha do
  path = '../app/build.gradle'
  re = /versionCode\s+(\d+)/ 
  androidBuildGradleFileContent = File.read(path)
  versionCode = (androidBuildGradleFileContent[re, 1].to_i+1)
  androidBuildGradleFileContent[re, 1] = versionCode.to_s
  androidBuildGradleFile = File.new(path, 'w')
  androidBuildGradleFile.write(androidBuildGradleFileContent)
  androidBuildGradleFile.close
  gradle(
    task: "assemble",
    build_type: "Release",
  )
  hockey(api_token: ENV["HOCKEY_APP_API_TOKEN"])
end

  after_all do |lane|
     slack(channel: "fastlane", message: "Successfully build new Android App.”)
  end

  error do |lane, exception|
     slack(
       message: exception.message,
       success: false
     )
  end
end
